# Generated by Django 4.1.1 on 2022-11-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idJuego', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('consola', models.CharField(max_length=25)),
                ('genero', models.CharField(max_length=10)),
                ('an_o', models.IntegerField()),
                ('clasificacion', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPelicula', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=10)),
                ('an_o', models.IntegerField()),
                ('clasificacion', models.CharField(max_length=10)),
            ],
        ),
    ]
