# Generated by Django 4.1.1 on 2022-11-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlockBuster', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juego',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='id',
        ),
        migrations.AlterField(
            model_name='juego',
            name='idJuego',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='idPelicula',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
