# Generated by Django 4.1.1 on 2022-12-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlockBuster', '0003_libro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('idG', models.IntegerField(primary_key=True, serialize=False)),
                ('genero', models.CharField(max_length=20)),
                ('tipo', models.CharField(max_length=20)),
            ],
        ),
    ]
