# Generated by Django 4.1.1 on 2022-10-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id_certificado', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('curso', models.CharField(max_length=30)),
                ('version', models.CharField(max_length=15)),
                ('id_verificacion', models.CharField(max_length=15)),
            ],
        ),
    ]
